### ISSUE TITLE
Is there a good module for counting the number of parameters of a model?

### ISSUE THREAD

**Issue by Heonjin** [j-marple-dev/model_compression#10]
There is a "[pytorch-summary](https://github.com/sksq96/pytorch-summary)" module in python and it counts how many params the model has. I wonder how you count params of a prunned model. If there're any tips for checking model's information like "pytroch-sumary", please let me know.
Thanks in advance.

**Comment by Curt-Park** [comment]
We implemented a function to count model parameters. Check the following lines:

https://github.com/j-marple-dev/model_compression/blob/master/src/models/utils.py#L267

**Comment by hihunjin** [comment]
Thanks. I found that you shrank your model and just count all params in the model!

**Comment by Curt-Park** [comment]
Yes, right. Let me know if you have any more question, otherwise please close the issue. :)
