### ISSUE TITLE
densenet_121 학습 문제

### ISSUE THREAD

**Issue by godhj93** [j-marple-dev/model_compression#15]
`python train.py --config config/train/cifar100/densenet_121.py `

**docker로 densenet_121 학습 시 다음과 같은 에러가 나오면서 진행 불가합니다. 다른 버전의 Densenet은 잘 학습됩니다.**

> user@2605b03c4c53:/app/model_compression$ python train.py --config config/train/cifar100/densenet_121.py 
> 2021-03-04 13:08:56,255 - config_validator.py:44 - INFO - [Config]	SEED: 777	AUG_TRAIN: randaugment_train_cifar100_224	AUG_TRAIN_PARAMS: {'n_select': 2, 'level': None}	AUG_TEST: simple_augment_test_cifar100_224	CUTMIX: {'beta': 1, 'prob': 0.5}	DATASET: CIFAR100	MODEL_NAME: densenet	MODEL_PARAMS: {'num_classes': 100, 'inplanes': 24, 'growthRate': 32, 'compressionRate': 2, 'block_configs': (6, 12, 24, 16), 'small_input': False, 'efficient': False}	CRITERION: CrossEntropy	CRITERION_PARAMS: {'num_classes': 100, 'label_smoothing': 0.1}	LR_SCHEDULER: WarmupCosineLR	LR_SCHEDULER_PARAMS: {'warmup_epochs': 5, 'start_lr': 0.001, 'min_lr': 1e-05, 'n_rewinding': 1}	BATCH_SIZE: 128	LR: 0.1	MOMENTUM: 0.9	WEIGHT_DECAY: 0.0001	NESTEROV: True	EPOCHS: 300	N_WORKERS: 20
> 2021-03-04 13:08:57,516 - trainer.py:71 - INFO - Created a model densenet with 6.85M params
> 2021-03-04 13:08:57,516 - trainer.py:74 - INFO - Setup train configuration
> Files already downloaded and verified
> 2021-03-04 13:08:58,398 - trainer.py:98 - INFO - Datasets prepared
> 2021-03-04 13:08:58,398 - trainer.py:110 - INFO - Dataloader prepared
> [Train]	N/A% (0 of 391) |                                      | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
>   File "train.py", line 67, in <module>
>     trainer.run(args.resume)
>   File "/app/model_compression/src/runners/trainer.py", line 168, in run
>     self.run_one_epoch(self.epoch)
>   File "/app/model_compression/src/runners/trainer.py", line 179, in run_one_epoch
>     train_loss, train_stat = self.train_one_epoch()
>   File "/app/model_compression/src/runners/trainer.py", line 233, in train_one_epoch
>     loss, outputs = self.criterion(self.model, images=images, labels=labels)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/app/model_compression/src/criterions.py", line 166, in forward
>     logit = model(images)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/app/model_compression/src/models/densenet.py", line 170, in forward
>     return self._forward_impl(x)
>   File "/app/model_compression/src/models/densenet.py", line 162, in _forward_impl
>     x = self.dense_blocks(x)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
>     input = module(input)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/app/model_compression/src/models/densenet.py", line 76, in forward
>     new_features = layer(*features)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/app/model_compression/src/models/densenet.py", line 47, in forward
>     out = self._expand(*prev_features)
>   File "/app/model_compression/src/models/densenet.py", line 39, in _expand
>     bottleneck_output = self.conv1(concated_features)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/app/model_compression/src/models/common_layers.py", line 96, in forward
>     x = self.bn(x)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 106, in forward
>     exponential_average_factor, self.eps)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/functional.py", line 1923, in batch_norm
>     training, momentum, eps, torch.backends.cudnn.enabled
> RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 7.79 GiB total capacity; 4.02 GiB already allocated; 229.81 MiB free; 4.05 GiB reserved in total by PyTorch)
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/home/user/miniconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/home/user/miniconda/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
>     r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/queues.py", line 113, in get
>     return _ForkingPickler.loads(res)
>   File "/home/user/miniconda/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
>     fd = df.detach()
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
>     with _resource_sharer.get_connection(self._id) as conn:
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
>     c = Client(address, authkey=process.current_process().authkey)
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/connection.py", line 498, in Client
>     answer_challenge(c, authkey)
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
>     message = connection.recv_bytes(256)         # reject large message
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
>     buf = self._recv_bytes(maxlength)
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
>     buf = self._recv(4)
>   File "/home/user/miniconda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
>     chunk = read(handle, remaining)
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> [Train]	100% (391 of 391) |####################################| Elapsed Time: 0:00:01 Time:  0:00:01
> user@2605b03c4c53:/app/model_compression$ 
>

**Comment by Curt-Park** [comment]
사용하시는 GPU의 메모리가 부족해서 발생하는 문제입니다. 좀 더 작은 크기의 모델로 시도해보시면 될 것 같습니다.
